/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e332ddb445d1d2359cb8f45c3b0d2a8a (do not edit this line) */
