/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffe2db907262d68c98be4074cb01f38b (do not edit this line) */
