/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a61d2bc3df413fea3acbf8ad4953c41 (do not edit this line) */
