/* Generated By:JJTree: Do not edit this line. ASTBitXor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBitXor extends SimpleNode {
  public ASTBitXor(int id) {
    super(id);
  }

  public ASTBitXor(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=824b2fadd789c9bf7c1869169ad8c4c8 (do not edit this line) */
