/* Generated By:JJTree: Do not edit this line. ASTBitOr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBitOr extends SimpleNode {
  public ASTBitOr(int id) {
    super(id);
  }

  public ASTBitOr(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d894d485efb9d2359b08f91556ccb081 (do not edit this line) */
