/* Generated By:JJTree: Do not edit this line. ASTBitAnd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBitAnd extends SimpleNode {
  public ASTBitAnd(int id) {
    super(id);
  }

  public ASTBitAnd(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=419586359e5c4886d9aa5b51c6719649 (do not edit this line) */
