/* Generated By:JJTree: Do not edit this line. ASTEqual.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=888c7e8be742e4716e4c1dafb91f6111 (do not edit this line) */
