/* Generated By:JJTree: Do not edit this line. ASTForInit.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ccf506ac2fd1eac506a7300344275973 (do not edit this line) */
