/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a633c405f0f40c55a6476e7128c473d9 (do not edit this line) */
