/* Generated By:JJTree: Do not edit this line. ASTFor.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTFor extends SimpleNode {
  public ASTFor(int id) {
    super(id);
  }

  public ASTFor(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae458ed5d815d8ec061eb712ccbe9407 (do not edit this line) */
