/* Generated By:JJTree: Do not edit this line. ASTForStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=505b243b7a4c2196b894a081f0301dea (do not edit this line) */
