/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b313f61b6a63267d2d9678a64e991a6f (do not edit this line) */
