/* Generated By:JJTree: Do not edit this line. ASTIf.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIf extends SimpleNode {
  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de1b72ff1a6bf8ba4b425531f431c7a4 (do not edit this line) */
