/* Generated By:JJTree: Do not edit this line. ASTIfElseStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIfElseStatement extends SimpleNode {
  public ASTIfElseStatement(int id) {
    super(id);
  }

  public ASTIfElseStatement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ea5e3d7f09573b04819b5910a3beb6f (do not edit this line) */
