/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db5cd3b55d9e9147f85a6bc04a2c16d0 (do not edit this line) */
