/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5d6e745b46d336488f3719896705a31 (do not edit this line) */
