/* Generated By:JJTree: Do not edit this line. ASTIfElse.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTIfElse extends SimpleNode {
  public ASTIfElse(int id) {
    super(id);
  }

  public ASTIfElse(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84532070d6932cc33b2ca7c5097dc6c1 (do not edit this line) */
