/* Generated By:JJTree: Do not edit this line. ASTMethodBody.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMethodBody extends SimpleNode {
  public ASTMethodBody(int id) {
    super(id);
  }

  public ASTMethodBody(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05ed7cd88f2a6d7c8c9c4675db4ef2ba (do not edit this line) */
