/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5982b3c1962ac3c02179348306acf51a (do not edit this line) */
