/* Generated By:JJTree: Do not edit this line. ASTOr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffceda279a737b3f89ce6d8bb0169ffc (do not edit this line) */
