/* Generated By:JJTree: Do not edit this line. ASTPreIncrement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPreIncrement extends SimpleNode {
  public ASTPreIncrement(int id) {
    super(id);
  }

  public ASTPreIncrement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a92fead1b7e6ad82ae23b331cf63b205 (do not edit this line) */
