/* Generated By:JJTree: Do not edit this line. ASTQualifiedIdentifierList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTQualifiedIdentifierList extends SimpleNode {
  public ASTQualifiedIdentifierList(int id) {
    super(id);
  }

  public ASTQualifiedIdentifierList(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d0c0643058d7529d270a055a9335001 (do not edit this line) */
