/* Generated By:JJTree: Do not edit this line. ASTRelational.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTRelational extends SimpleNode {
  public ASTRelational(int id) {
    super(id);
  }

  public ASTRelational(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8eb6a119c4672d0441b00c45695c20b3 (do not edit this line) */
