/* Generated By:JJTree: Do not edit this line. ASTShift.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTShift extends SimpleNode {
  public ASTShift(int id) {
    super(id);
  }

  public ASTShift(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=570bf1a374109a210d7637ffb61367c4 (do not edit this line) */
