/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTStatement extends SimpleNode {
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56f4ddcbe036f012aaf129947680a7e7 (do not edit this line) */
