/* Generated By:JJTree: Do not edit this line. ASTUnary.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTUnary extends SimpleNode {
  public ASTUnary(int id) {
    super(id);
  }

  public ASTUnary(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be46586a68d32cc6c149ce80d3aa2cb7 (do not edit this line) */
