/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a0b0303f5ac2d7fa2e70f663199a250 (do not edit this line) */
