/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(Program p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a187a063af2ebfc0c10b77415819ae6b (do not edit this line) */
