/* Generated By:JavaCC: Do not edit this line. ProgramTreeConstants.java Version 4.1d1 */
public interface ProgramTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTBITOR = 4;
  public int JJTBITXOR = 5;
  public int JJTBITAND = 6;
  public int JJTEQUAL = 7;
  public int JJTRELATIONAL = 8;
  public int JJTSHIFT = 9;
  public int JJTADD = 10;
  public int JJTMULT = 11;
  public int JJTUNARY = 12;
  public int JJTPREINCREMENT = 13;
  public int JJTPREDECREMENT = 14;
  public int JJTIDENTIFIER = 15;
  public int JJTINTEGER = 16;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Or",
    "And",
    "BitOr",
    "BitXor",
    "BitAnd",
    "Equal",
    "Relational",
    "Shift",
    "Add",
    "Mult",
    "Unary",
    "PreIncrement",
    "PreDecrement",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=96311a799566e13a41d9608ecd09ed2e (do not edit this line) */
