/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ABSTRACT = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int INSTANCE_INIT = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int BYTE = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int CATCH = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CONST = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int _DEFAULT = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int FINAL = 25;
  /** RegularExpression Id. */
  int FINALLY = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int GOTO = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int IFELSE = 31;
  /** RegularExpression Id. */
  int IMPLEMENTS = 32;
  /** RegularExpression Id. */
  int IMPORT = 33;
  /** RegularExpression Id. */
  int INSTANCEOF = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int INTERFACE = 36;
  /** RegularExpression Id. */
  int LONG = 37;
  /** RegularExpression Id. */
  int NATIVE = 38;
  /** RegularExpression Id. */
  int NEW = 39;
  /** RegularExpression Id. */
  int NULL = 40;
  /** RegularExpression Id. */
  int PACKAGE = 41;
  /** RegularExpression Id. */
  int PRIVATE = 42;
  /** RegularExpression Id. */
  int PROTECTED = 43;
  /** RegularExpression Id. */
  int PUBLIC = 44;
  /** RegularExpression Id. */
  int RETURN = 45;
  /** RegularExpression Id. */
  int SHORT = 46;
  /** RegularExpression Id. */
  int STATIC = 47;
  /** RegularExpression Id. */
  int SUPER = 48;
  /** RegularExpression Id. */
  int SWITCH = 49;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 50;
  /** RegularExpression Id. */
  int THIS = 51;
  /** RegularExpression Id. */
  int THROW = 52;
  /** RegularExpression Id. */
  int THROWS = 53;
  /** RegularExpression Id. */
  int TRANSIENT = 54;
  /** RegularExpression Id. */
  int TRUE = 55;
  /** RegularExpression Id. */
  int TRY = 56;
  /** RegularExpression Id. */
  int VOID = 57;
  /** RegularExpression Id. */
  int VOLATILE = 58;
  /** RegularExpression Id. */
  int WHILE = 59;
  /** RegularExpression Id. */
  int STRICTFP = 60;
  /** RegularExpression Id. */
  int _OPTIONS = 61;
  /** RegularExpression Id. */
  int _LOOKAHEAD = 62;
  /** RegularExpression Id. */
  int _EOF = 63;
  /** RegularExpression Id. */
  int STRING = 64;
  /** RegularExpression Id. */
  int ID = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int REAL = 67;
  /** RegularExpression Id. */
  int LBRACKET = 68;
  /** RegularExpression Id. */
  int RBRACKET = 69;
  /** RegularExpression Id. */
  int COMMA = 70;
  /** RegularExpression Id. */
  int LPAREN = 71;
  /** RegularExpression Id. */
  int RPAREN = 72;
  /** RegularExpression Id. */
  int LBRACE = 73;
  /** RegularExpression Id. */
  int RBRACE = 74;
  /** RegularExpression Id. */
  int SEMICOLON = 75;
  /** RegularExpression Id. */
  int DOT = 76;
  /** RegularExpression Id. */
  int PLUS = 77;
  /** RegularExpression Id. */
  int MINUS = 78;
  /** RegularExpression Id. */
  int MULTIPLY = 79;
  /** RegularExpression Id. */
  int DIVIDE = 80;
  /** RegularExpression Id. */
  int ASSIGN = 81;
  /** RegularExpression Id. */
  int MODULO = 82;
  /** RegularExpression Id. */
  int EQ = 83;
  /** RegularExpression Id. */
  int NOTEQ = 84;
  /** RegularExpression Id. */
  int LT = 85;
  /** RegularExpression Id. */
  int LEQ = 86;
  /** RegularExpression Id. */
  int GT = 87;
  /** RegularExpression Id. */
  int GEQ = 88;
  /** RegularExpression Id. */
  int AND = 89;
  /** RegularExpression Id. */
  int NOT = 90;
  /** RegularExpression Id. */
  int OR = 91;
  /** RegularExpression Id. */
  int BIT_AND = 92;
  /** RegularExpression Id. */
  int BIT_OR = 93;
  /** RegularExpression Id. */
  int BIT_NOT = 94;
  /** RegularExpression Id. */
  int XOR = 95;
  /** RegularExpression Id. */
  int LSHIFT = 96;
  /** RegularExpression Id. */
  int RSHIFT = 97;
  /** RegularExpression Id. */
  int URSHIFT = 98;
  /** RegularExpression Id. */
  int INCREMENT = 99;
  /** RegularExpression Id. */
  int DECREMENT = 100;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"//\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"abstract\"",
    "\"boolean\"",
    "\"instance_init\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"ifelse\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "\"options\"",
    "\"LOOKAHEAD\"",
    "\"EOF\"",
    "<STRING>",
    "<ID>",
    "<DIGIT>",
    "<REAL>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"%\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"^\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"++\"",
    "\"--\"",
    "\"id\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"?\"",
    "\":\"",
  };

}
